# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
process_text <- function(text, construct_delimiter, constituent_delimiter, subconstituent_delimiter, discontinued_constituent_delimiter_begin, discontinued_constituent_delimiter_end) {
    .Call(`_menzerath_process_text`, text, construct_delimiter, constituent_delimiter, subconstituent_delimiter, discontinued_constituent_delimiter_begin, discontinued_constituent_delimiter_end)
}

