# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Process annotated text
#'
#' @param text string
#' @param construct_delimiter char
#' @param constituent_delimiter char
#' @param subconstituent_delimiter char
#' @param discontinued_constituent_delimiter_begin char
#' @param discontinued_constituent_delimiter_end char
#' @return data.frame A data.frame with three columns: constituents, subconstituents and constructs
#' @examples
#' annotated_text <- paste0("Greece* {which* is* the* most* beau*ti*ful* coun*try*",
#'                         " +I* know* +}was* the* first* place* +we* vi*si*ted* in*",
#'                         "Eu*ro*pe* +.")
#'  counts_df <- process_text(annotated_text, "+", " ", "*", "{", "}")
#' @export
process_text <- function(text, construct_delimiter, constituent_delimiter, subconstituent_delimiter, discontinued_constituent_delimiter_begin, discontinued_constituent_delimiter_end) {
    .Call(`_menzerath_process_text`, text, construct_delimiter, constituent_delimiter, subconstituent_delimiter, discontinued_constituent_delimiter_begin, discontinued_constituent_delimiter_end)
}

